baseURL = 'https://trimad.github.io'
languageCode = 'en-us'
title = 'Ghostfeed'

theme = "GhostGraph"

relativeURLs = false
canonifyURLs = true

enableGitInfo = true

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[params]
  description = "Ghostfeed: Ghost in the Shell-inspired notes, experiments, and troubleshooting posts."
  # Add other site-wide parameters here

# Enable robots.txt and sitemap generation (usually enabled by default)
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
