[[main]]
  name = "Home"
  url = ""
  weight = -100

[[main]]
  name = "TheraFit"
  url = "/therafit/"
  weight = -50

[[main]]
  name = "Archives"
  url = "/archives/"
  weight = 0

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Shop"
  identifier = "Shop"
  weight = 50

[[main]]
  parent = "Shop"
  name = "RedBubble"
  url = "https://www.redbubble.com/people/3leet5u/shop"
  weight = 1

[[main]]
  parent = "Shop"
  name = "Society6"
  url = "https://society6.com/trimad"
  weight = 2

[[main]]
  parent = "Shop"
  name = "Threadless"
  url = "https://www.threadless.com/search?artist=3leet5u"
  weight = 3